### ISSUE TITLE
RP2350 support

### ISSUE THREAD

**Issue by leondisctech** [raspberrypi/pico-tflmicro#18] opened 2024-08-15 15:11 UTC
Hi @petewarden 

I realize that the Pico 2 (and RP2350 chip) aren't widely available yet, so it may not be possible to answer this question yet, but I'll ask anyway:

Will pico-tflmicro will work out of the box with the RP2350 or if it will take some tweaking?

(I recall that getting two cores to work on the RP2040 required digging into the details of the RP2040's memory layout, so supporting the RP2350 may require something similar.)

**Comment by Hedda** [comment] 2024-10-25 06:44
+1 Please add [Platform Support](https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/docs/new_platform_support.md) for RP2350 (Raspberry Pi Pico 2):

* https://github.com/raspberrypi/pico-tflmicro

  * https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/docs/new_platform_support.md

Preferably also update from upstream [pico-tflmicro](https://github.com/raspberrypi/pico-tflmicro) as well:

- https://github.com/raspberrypi/pico-tflmicro/issues/20

Add platform support for the new RP2350 MCU and the official Raspberry Pi Pico 2 development board:

* https://www.raspberrypi.com/products/rp2350/
- https://datasheets.raspberrypi.com/rp2350/rp2350-datasheet.pdf
- https://www.raspberrypi.com/products/raspberry-pi-pico-2/

RP2350 is the successor and next-generation of RPi RP2040 so guess would need to update the RP2040 platform for it or add another platform? And if you do please post a new blog post to announce the updated and added RP2350 support!

* * https://www.raspberrypi.com/news/a-big-bang-update-for-tensorflow-lite-for-microcontrollers/

Raspberry Pi Pico 2 with Wi-Fi and other developer boards from Raspberry Pi's partners should hopefully be made available soon and at least the RP2350 SoC itself is now available for those wanting to build their own board and said to become even more generally available in volume before the end of 2024. To register your interest, and to participate in the Raspberry Pi samples program, head over to the [product page](https://www.raspberrypi.com/products/rp2350/).

FYI, a "W" version of the Pico 2 with wireless support are expected 'by the end of the year' according the people in the know 😛

Note that there is also not yet an official Raspberry Pi Pico 2 board with Wi-Fi but there are third-party boards with WiFi and LAN, see:

* https://www.raspberrypi.com/news/our-rp2350-partners-made-all-this-excellent-stuff-for-you/
  * https://www.raspberrypi.com/for-industry/powered-by/product-catalogue/?category=RP2350
    * https://ilabs.se/?s=RP2350&post_type=product
    * https://docs.wiznet.io/Product/iEthernet/W6100/w6100-evb-pico2

Raspberry Pi team have written that the new [RP2350](https://www.raspberrypi.com/products/rp2350/) is vastly more sophisticated design than RP2040, however I understand it is supposedly backwards-compatible, though this new model now also offers faster resources, more IO/PIO,  support for Arm TrustZone (security architecture), new HSTX peripheral for high-speed data transmission, and support for external QSPI PSRAM.

RP2350 microcontroller also adds an HSTX (High-Speed Serial Transmit) interface adding the PIOs (Programmable IOs) that was introduced on the original Raspberry Pi RP2040 MCU three years ago. The RP2350 MCU now has three PIOs and one HSTX interface going over 8x GPIOs.

However, I believe that the most interesting difference is otherwise probably the fact that the new Raspberry Pi RP2350 MCU features two-modes with dual-core RISC-V or dual-core ARM Cortex-M33 on the chip, meaning that you can either choose to run it in either RISC-V mode or in ARM Cortex-M3 mode, (but not more than two cores active at the same time, meaning that you can actually run in mixed mode with one RISC-V core and one ARM Cortex-M33 core which is probably something that is both unique and a first for a such SoC, so **_"They're selectable at boot time: Each port into the bus fabric can be connected either to an M33 or a Hazard3 via a mux. You can even, if you're feeling obtuse, run with one of each."_** Arm/RISC-V switching is explained in the official datasheet:

* https://www.raspberrypi.com/news/raspberry-pi-pico-2-our-new-5-microcontroller-board-on-sale-now/
* https://www.raspberrypi.com/products/raspberry-pi-pico-2/
* https://www.raspberrypi.com/documentation/microcontrollers/pico-series.html#pinout-and-design-files
* https://www.raspberrypi.com/products/rp2350/
* https://datasheets.raspberrypi.com/rp2350/rp2350-datasheet.pdf
* https://github.com/raspberrypi/pico-sdk-rp2350
* https://github.com/raspberrypi/pico-examples-rp2350
* https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf
* https://github.com/raspberrypi/pico-vscode

Many RP2350-based development baords and products are already apparently already in the pipeline:

https://www.raspberrypi.com/for-industry/powered-by/product-catalogue/?category=RP2350

If official Pico2 is hard to find then be ware that SparkFun Pro Micro RP2350 (and DEV-24870)  and Adafruit Feather RP2350 (Product ID: 6000) are supposedly among the first of third-parties  scheduled to become available to the first third-party boards available with RP2350:

* https://www.sparkfun.com/products/24870

* https://www.adafruit.com/product/6000

This article from CNX software offers a little more insight into the RP2350 as compared to the RP2040:

* https://www.cnx-software.com/2024/08/08/raspberry-pi-pico-2-raspberry-pi-rp2350-dual-core-risc-v-or-arm-cortex-m33-microcontroller/

"**_The RP2350 embeds both an open-source Hazard3 RISC-V dual-core CPU and a dual-core Cortex-M33, but only one cluster can be used at a given time. Apart from the faster MCU cores and higher SRAM capacity, the RP2350 is about the same as the RP2040, albeit it also adds one extra PIO block bringing the total to three. One important new feature is built-in security when using Arm Cortex-M33 cores with Trustzone and other security features._**"

**_As I understand it, the RP2350A package offers also the same pinout as the RP2040 microcontroller, but the company now also adding a larger RP2350B package with additional GPIOs and analog inputs._**

_**Raspberry Pi used the same method as for the RP2040 to derive the RP2350 name. RP stands for “Raspberry Pi”, “2” is the number of cores, “3” refers to the MCU core used (e.g. Cortex-M33), and the last two numbers “4” and “0” use floor(log2(x/16k)) formula to calculate a number representing the SRAM and non-volatile storage capacity inside the chip.**_

* https://www.raspberrypi.com/documentation/microcontrollers/silicon.html#architecture-switching

![image](https://github.com/user-attachments/assets/e03a40d5-17f2-431c-a41f-7e398da4c07f)

![image](https://github.com/user-attachments/assets/fa76c023-9154-40ef-a20e-b5bdf2b3cdd4)

![image](https://github.com/user-attachments/assets/43240951-ed2b-405b-bad7-4cb23663cdd3)

![image](https://github.com/user-attachments/assets/deaa0ede-75f4-46a9-a314-011f4c34c1cf)

![image](https://github.com/user-attachments/assets/7ffa20f1-2c26-4850-b3cc-0226a396b618)

PS: RP2350 is newly released so there is not yet widespread support but RP2040 based development boards are already very popular in schools and STEM education so think they are interesting as alternatives to ESP32 because documentation is often easier as often targeting beginners which in turn means can lead to broader use and use cases.

**Comment by Hedda** [comment] 2024-12-16 14:35
@petewarden Any chance of getting the Pico2 / RP2350 pull request #19 with patch by @sean-lawless merged into main? 

- https://github.com/raspberrypi/pico-tflmicro/pull/19

**Comment by petewarden** [comment] 2024-12-24 07:35
I've pulled in the latest SDK in https://github.com/raspberrypi/pico-tflmicro/commit/82ee61dfddc56cc9b6d47785ea6a7975c432e972  and confirmed the binaries produced run on an RP2350.

I'm now working on pulling in the last few months of upstream changes, I'll update this thread once that's done.

**Comment by petewarden** [comment] 2024-12-27 03:03
I've now pulled the latest upstream changes and confirmed they work on the RP2350. See https://github.com/raspberrypi/pico-tflmicro/commit/dfea53b977f131dc50d7060568ad4fd355d4d71e

I'm closing this as fixed, but please reopen (or file a new issue) if there are other RP2350 problems.

**Closed as completed by petewarden** 2024-12-27 03:03 UTC
